# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decryption_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_decryption_screen(object):
    def setupUi(self, decryption_screen):
        decryption_screen.setObjectName("decryption_screen")
        decryption_screen.resize(1810, 1018)
        decryption_screen.setStyleSheet("background-color: rgb(190, 222, 255);\n"
"")
        self.frame = QtWidgets.QFrame(decryption_screen)
        self.frame.setGeometry(QtCore.QRect(330, 10, 1351, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(580, 10, 501, 51))
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(decryption_screen)
        self.label_9.setGeometry(QtCore.QRect(370, 140, 171, 31))
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(decryption_screen)
        self.textBrowser.setGeometry(QtCore.QRect(110, 220, 691, 621))
        self.textBrowser.setToolTipDuration(0)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")
        self.line_4 = QtWidgets.QFrame(decryption_screen)
        self.line_4.setGeometry(QtCore.QRect(360, 170, 181, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_2 = QtWidgets.QLabel(decryption_screen)
        self.label_2.setGeometry(QtCore.QRect(1280, 110, 231, 41))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(decryption_screen)
        self.frame_2.setGeometry(QtCore.QRect(1000, 170, 771, 781))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 121, 31))
        self.label_3.setObjectName("label_3")
        self.name_line = QtWidgets.QLineEdit(self.frame_2)
        self.name_line.setGeometry(QtCore.QRect(140, 80, 361, 31))
        self.name_line.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.name_line.setInputMask("")
        self.name_line.setText("")
        self.name_line.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.name_line.setObjectName("name_line")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(350, 220, 111, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 310, 121, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_file = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_file.setGeometry(QtCore.QRect(200, 310, 361, 31))
        self.lineEdit_file.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.btn_browser = QtWidgets.QPushButton(self.frame_2)
        self.btn_browser.setGeometry(QtCore.QRect(600, 310, 141, 41))
        self.btn_browser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_browser.setAutoDefault(False)
        self.btn_browser.setDefault(False)
        self.btn_browser.setFlat(False)
        self.btn_browser.setObjectName("btn_browser")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(30, 430, 161, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_private_key_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_private_key_2.setGeometry(QtCore.QRect(200, 430, 351, 31))
        self.lineEdit_private_key_2.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.lineEdit_private_key_2.setObjectName("lineEdit_private_key_2")
        self.btn_browser_2 = QtWidgets.QPushButton(self.frame_2)
        self.btn_browser_2.setGeometry(QtCore.QRect(600, 430, 141, 41))
        self.btn_browser_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_browser_2.setAutoDefault(False)
        self.btn_browser_2.setDefault(False)
        self.btn_browser_2.setFlat(False)
        self.btn_browser_2.setObjectName("btn_browser_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 540, 181, 31))
        self.label_8.setObjectName("label_8")
        self.lineEdit_key_encrypted_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_key_encrypted_3.setGeometry(QtCore.QRect(210, 540, 351, 31))
        self.lineEdit_key_encrypted_3.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.lineEdit_key_encrypted_3.setObjectName("lineEdit_key_encrypted_3")
        self.btn_browser_3 = QtWidgets.QPushButton(self.frame_2)
        self.btn_browser_3.setGeometry(QtCore.QRect(600, 530, 141, 41))
        self.btn_browser_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_browser_3.setAutoDefault(False)
        self.btn_browser_3.setDefault(False)
        self.btn_browser_3.setFlat(False)
        self.btn_browser_3.setObjectName("btn_browser_3")
        self.btn_dechiffrer = QtWidgets.QPushButton(self.frame_2)
        self.btn_dechiffrer.setGeometry(QtCore.QRect(310, 660, 181, 41))
        self.btn_dechiffrer.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.btn_dechiffrer.setObjectName("btn_dechiffrer")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(330, 250, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(decryption_screen)
        self.line.setGeometry(QtCore.QRect(883, 200, 20, 801))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(decryption_screen)
        QtCore.QMetaObject.connectSlotsByName(decryption_screen)

    def retranslateUi(self, decryption_screen):
        _translate = QtCore.QCoreApplication.translate
        decryption_screen.setWindowTitle(_translate("decryption_screen", "Form"))
        self.label.setText(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">CHIFFREMENT HYBRIDE </span></p></body></html>"))
        self.label_9.setText(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">INSTRUCTIONS</span></p><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.textBrowser.setHtml(_translate("decryption_screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">🔓 Tutoriel pour déchiffrer un message</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Lorsque vous avez chiffré votre message, trois fichiers ont été générés automatiquement :</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">📄 Le <span style=\" font-weight:600;\">message chiffré</span></li>\n"
"<li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🔐 La <span style=\" font-weight:600;\">clé chiffrée</span></li>\n"
"<li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🔑 La <span style=\" font-weight:600;\">clé publique</span></li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Pour pouvoir déchiffrer ce message, vous avez besoin des </span><span style=\" font-size:11pt; font-weight:600;\">deux clés</span><span style=\" font-size:11pt;\"> (chiffrée et privée) ainsi que du </span><span style=\" font-size:11pt; font-weight:600;\">message chiffré</span><span style=\" font-size:11pt;\">.</span></p>\n"
"<hr />\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">✅ Étapes à suivre pour le déchiffrement :</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Renseignez les champs requis :</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">La <span style=\" font-weight:600;\">clé chiffrée </span></li>\n"
"<li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">La <span style=\" font-weight:600;\">clé privée </span></li>\n"
"<li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Le <span style=\" font-weight:600;\">message chiffré</span></li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><span style=\" font-size:11pt;\">⚠️ </span><span style=\" font-size:11pt; font-weight:600;\">Attention :</span><span style=\" font-size:11pt;\"> Utilisez uniquement les clés d\'origine. Si vous utilisez une mauvaise clé, le message ne pourra pas être déchiffré correctement.</span></p>\n"
"<li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Entrez votre nom d\'utilisateur.</span></li>\n"
"<li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Le résultat du déchiffrement sera automatiquement enregistré sur votre <span style=\" font-weight:600;\">Bureau</span>, dans un fichier nommé <span style=\" font-family:\'Courier New\'; font-weight:600;\">decryption_resultat + username.txt</span>.</li></ol></body></html>"))
        self.label_2.setText(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">FILE DECRYTION</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:12pt;\">username :</span></p></body></html>"))
        self.name_line.setPlaceholderText(_translate("decryption_screen", "votre nom ..."))
        self.label_5.setText(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:11pt;\">FILE PATH</span></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">FILE PATH :</span></p></body></html>"))
        self.lineEdit_file.setPlaceholderText(_translate("decryption_screen", " Le message chiffré "))
        self.btn_browser.setWhatsThis(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:12pt;\">chiffrer</span></p></body></html>"))
        self.btn_browser.setText(_translate("decryption_screen", "parcourir"))
        self.label_7.setText(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">private key PATH :</span></p></body></html>"))
        self.lineEdit_private_key_2.setPlaceholderText(_translate("decryption_screen", " La clé privée "))
        self.btn_browser_2.setWhatsThis(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:12pt;\">chiffrer</span></p></body></html>"))
        self.btn_browser_2.setText(_translate("decryption_screen", "parcourir"))
        self.label_8.setText(_translate("decryption_screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#000000;\">encrypted key PATH :</span></p></body></html>"))
        self.lineEdit_key_encrypted_3.setPlaceholderText(_translate("decryption_screen", " La clé chiffrée "))
        self.btn_browser_3.setWhatsThis(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:12pt;\">chiffrer</span></p></body></html>"))
        self.btn_browser_3.setText(_translate("decryption_screen", "parcourir"))
        self.btn_dechiffrer.setWhatsThis(_translate("decryption_screen", "<html><head/><body><p><span style=\" font-size:12pt;\">chiffrer</span></p></body></html>"))
        self.btn_dechiffrer.setText(_translate("decryption_screen", "EXECUTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    decryption_screen = QtWidgets.QWidget()
    ui = Ui_decryption_screen()
    ui.setupUi(decryption_screen)
    decryption_screen.show()
    sys.exit(app.exec_())
