# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_encryption_screen(object):
    def setupUi(self, encryption_screen):
        encryption_screen.setObjectName("encryption_screen")
        encryption_screen.resize(1738, 1091)
        encryption_screen.setStyleSheet("background-color: rgb(190, 222, 255);")
        self.frame = QtWidgets.QFrame(encryption_screen)
        self.frame.setGeometry(QtCore.QRect(230, 10, 1411, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(640, 20, 501, 51))
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(encryption_screen)
        self.frame_2.setGeometry(QtCore.QRect(970, 160, 711, 931))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 121, 31))
        self.label_3.setObjectName("label_3")
        self.name_line = QtWidgets.QLineEdit(self.frame_2)
        self.name_line.setGeometry(QtCore.QRect(190, 160, 291, 31))
        self.name_line.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.name_line.setInputMask("")
        self.name_line.setText("")
        self.name_line.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.name_line.setObjectName("name_line")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(320, 60, 101, 31))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(310, 90, 118, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(320, 300, 111, 31))
        self.label_5.setObjectName("label_5")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(300, 320, 118, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 390, 121, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(320, 720, 101, 31))
        self.label_7.setObjectName("label_7")
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(320, 750, 91, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(90, 810, 81, 31))
        self.label_8.setObjectName("label_8")
        self.line_key = QtWidgets.QLineEdit(self.frame_2)
        self.line_key.setGeometry(QtCore.QRect(190, 800, 351, 41))
        self.line_key.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.line_key.setObjectName("line_key")
        self.btn_chiffrer = QtWidgets.QPushButton(self.frame_2)
        self.btn_chiffrer.setGeometry(QtCore.QRect(280, 630, 181, 41))
        self.btn_chiffrer.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.btn_chiffrer.setObjectName("btn_chiffrer")
        self.btn_browser = QtWidgets.QPushButton(self.frame_2)
        self.btn_browser.setGeometry(QtCore.QRect(520, 390, 141, 41))
        self.btn_browser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_browser.setAutoDefault(False)
        self.btn_browser.setDefault(False)
        self.btn_browser.setFlat(False)
        self.btn_browser.setObjectName("btn_browser")
        self.lineEdit_file = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_file.setGeometry(QtCore.QRect(160, 390, 331, 41))
        self.lineEdit_file.setStyleSheet("background-color: rgb(235, 242, 255);")
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.label_2 = QtWidgets.QLabel(encryption_screen)
        self.label_2.setGeometry(QtCore.QRect(1280, 100, 281, 41))
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(encryption_screen)
        self.label_9.setGeometry(QtCore.QRect(450, 160, 141, 20))
        self.label_9.setObjectName("label_9")
        self.line_4 = QtWidgets.QFrame(encryption_screen)
        self.line_4.setGeometry(QtCore.QRect(430, 180, 161, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.textBrowser = QtWidgets.QTextBrowser(encryption_screen)
        self.textBrowser.setGeometry(QtCore.QRect(180, 210, 601, 691))
        self.textBrowser.setToolTipDuration(0)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(encryption_screen)
        QtCore.QMetaObject.connectSlotsByName(encryption_screen)

    def retranslateUi(self, encryption_screen):
        _translate = QtCore.QCoreApplication.translate
        encryption_screen.setWindowTitle(_translate("encryption_screen", "Form"))
        self.label.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">CHIFFREMENT HYBRIDE </span></p></body></html>"))
        self.label_3.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:12pt;\">username :</span></p></body></html>"))
        self.name_line.setPlaceholderText(_translate("encryption_screen", "votre nom ..."))
        self.label_4.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:10pt;\">identification</span></p></body></html>"))
        self.label_5.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:11pt;\">FILE PATH</span></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">FILE PATH :</span></p></body></html>"))
        self.label_7.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">KEY USED</span></p></body></html>"))
        self.label_8.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:10pt;\">Cle utilisé :</span></p></body></html>"))
        self.btn_chiffrer.setWhatsThis(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:12pt;\">chiffrer</span></p></body></html>"))
        self.btn_chiffrer.setText(_translate("encryption_screen", "EXECUTER"))
        self.btn_browser.setWhatsThis(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:12pt;\">chiffrer</span></p></body></html>"))
        self.btn_browser.setText(_translate("encryption_screen", "parcourir"))
        self.label_2.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">FILE ENCRYPTION</span></p></body></html>"))
        self.label_9.setText(_translate("encryption_screen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">INSTRUCTIONS</span></p><p><br/></p></body></html>"))
        self.textBrowser.setHtml(_translate("encryption_screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">📄 Tutoriel d\'utilisation de l\'application de chiffrement</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:10pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Écrivez votre message</span><br />Créez un fichier texte (<span style=\" font-family:\'Courier New\';\">.txt</span>) contenant le message que vous souhaitez chiffrer. (File path)</li>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<li style=\" font-size:10pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Clé générée automatiquement</span><br />Lors du chiffrement, une <span style=\" font-weight:600;\">clé</span> est créée automatiquement. Elle est composée de deux parties :</li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-size:10pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🔐 Une <span style=\" font-weight:600;\">clé chiffrée</span></li>\n"
"<li style=\" font-size:10pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🔑 Une <span style=\" font-weight:600;\">clé privée</span></li></ul>\n"
"<li style=\" font-size:10pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Résultat du chiffrement</span><br />Le message chiffré est enregistré dans un fichier <span style=\" font-family:\'Courier New\';\">.txt</span> sur votre <span style=\" font-weight:600;\">Bureau</span>, dans un dossier nommé <span style=\" font-family:\'Courier New\'; font-weight:600;\">encryption_result</span>, avec votre <span style=\" font-weight:600;\">nom d\'utilisateur</span> comme nom de fichier.</li>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<li style=\" font-size:10pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Sécurité des clés</span><br />Les clés sont <span style=\" font-weight:600;\">personnelles et confidentielles</span>.<br />➤ <span style=\" font-weight:600;\">Conservez-les précieusement</span> : elles sont nécessaires uniquement pour <span style=\" font-weight:600;\">déchiffrer</span> votre message.</li></ol></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    encryption_screen = QtWidgets.QWidget()
    ui = Ui_encryption_screen()
    ui.setupUi(encryption_screen)
    encryption_screen.show()
    sys.exit(app.exec_())
